shop/main/urls.py
from django.urls import path, include
from .import views

app_name = 'main'
urlpatterns = [
    path('index', views.index, name = 'index'),
    path('profile', views.profile, name = 'profile')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
]

shop/main/models.py
from django.db import models

# Create your models here.
class Owner(models.Model):
    username = models.CharField(max_length=50, verbose_name="Владелец")

    def __str__(self):
        return self.username

class Product(models.Model):
    # name
    # description
    # price
    # rating
    name = models.CharField(max_length=100, verbose_name='Название товара')
    description = models.TextField(verbose_name='Описание товара')
    price = models.FloatField(verbose_name='Стоимость товара')
    rating = models.FloatField(verbose_name='Рейтинг товара')
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}: {self.description}"

shop/main/views.py
from django.shortcuts import render

from .models import Product

# Create your views here.

def index(request):
    products = Product.objects.all()
    return render(request, 'main/index.html', {"products" : products})

def profile(request):
    return render(request, 'main/profile.html', {})

shop/main/templates/main/index.html
{% extends 'main/base.html'%}

{% block title %}
    Index page
{% endblock %}

{% block body %}
<br>
<br>
<a href="{% url 'main:profile' %}">Profile page</a>

{% if products %}
    {% for i in products %}
        <p>{{i.name }}</p>
        <p>{{i.description }}</p>
        <p>{{i.price }}</p>
        <p>{{i.rating }}</p>
    {% endfor %}
{% else %}
    <p>Магазин пуст</p>
{% endif %}
{% endblock %}